name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: sforge --version

      - name: Run Forge fmt
        run: sforge fmt --check

      - name: Run Forge build
        run: sforge build --sizes

      - name: Run Forge tests
        run: sforge test -vvv
